### ISSUE TITLE
lodash methods not found

### ISSUE THREAD

**Issue by hamidb** [ralucas/node-zillow#16]
I am running the example code on Mac OS. However, I am getting the following error:
```
Node-Zillow error:  TypeError: _.chain(...).map(...).map(...).map(...).fromPairs is not a function
    at handleResponse (/hamidb/applications/node-zillow/lib/helpers.js:99:8)
    at _fulfilled (/hamidb/applications/node-zillow/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/hamidb/applications/node-zillow/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/hamidb/applications/node-zillow/node_modules/q/q.js:816:13)
    at /hamidb/applications/node-zillow/node_modules/q/q.js:570:49
    at runSingle (/hamidb/applications/node-zillow/node_modules/q/q.js:137:13)
    at flush (/hamidb/applications/node-zillow/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by ralucas** [comment]
Can you try uninstalling and reinstalling the package?  It seems to be missing the lodash dependency.

**Comment by hamidb** [comment]
Thanks for quick response. In fact I did that.
It seems that the problem is with `.fromPairs` function. When I comment it, it is working fine. 
I installed **lodash 13.0.1**

**Comment by ralucas** [comment]
Do you have lodash globally installed?  The current version is 4.17.4 and the package.json calls for a 4.x version.
